version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: lightlist-db
    environment:
      POSTGRES_DB: lightlist_db
      POSTGRES_USER: lightlist_user
      POSTGRES_PASSWORD: lightlist_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  db-test:
    image: postgres:15-alpine
    container_name: lightlist-db-test
    environment:
      POSTGRES_DB: lightlist_test_db
      POSTGRES_USER: lightlist_user
      POSTGRES_PASSWORD: lightlist_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
  postgres_test_data: